apiVersion: v1
kind: Config
clusters:
- name: mock-cluster
  cluster:
    server: https://127.0.0.1:6443
    certificate-authority-data: PLACEHOLDER_BASE64_CA
contexts:
- name: mock-context
  context:
    cluster: mock-cluster
    user: mock-user
current-context: mock-context
users:
- name: mock-user
  user:
    client-certificate-data: PLACEHOLDER_BASE64_CERT
    client-key-data: PLACEHOLDER_BASE64_KEY