sut_path: "teastore"
docker_user: "cluereg.local:22222/karl"
local_public_ip: "cluere.local"
local_port: 8888
remote_platform_arch: "linux/arm64/v8"
local_platform_arch: "linux/amd64"

resource_limits:
  teastore-auth:
    cpu: 450
    memory: 1024
  teastore-webui:
    cpu: 1000
    memory: 1500
  teastore-recommender:
    cpu: 2000
    memory: 1024
  teastore-image:
    cpu: 1000
    memory: 1500
  teastore-all:
    cpu: 1500
    memory: 2048
default_resource_limits:
  cpu: 1000
  memory: 1024
workload_settings: {}
timeout_duration: 3600  # 1 hour in seconds
wait_before_workloads: 180  # 3 minutes in seconds
wait_after_workloads: 180  # 3 minutes in seconds
tags: []