# The main config for CLUE
config:
  ### BASE CONFIG ###
  # The main timeout to kill the experiment, to avoid hanging experiments
  experiment_timeout: 150
  
  ### NETWORKING CONFIG ###
  # The URL of the prometheus deployed on the host machine
  prometheus_url: "http://localhost:30090"
  
  ### GRAFANA CONFIG ###
  # Enable automatic Grafana dashboard import
  grafana_dashboard_import_enabled: true
  # Grafana admin credentials
  grafana_username: "admin"
  grafana_password: "prom-operator"
  # NodePort for Grafana service
  grafana_node_port: 30080
  # Path to the Kepler dashboard JSON file
  kepler_dashboard_path: "kepler_dashboard.json"
  
  ### DOCKER REGISTRY CONFIG ###
  # The URL of the docker registry deployed on the host machine
  docker_registry_address: "registry:5000"