config:
  prometheus_url: "http://host.internal:9090"
  docker_user: "host.internal:6789/clue"
  local_public_ip: "host.internal"
  local_port: 8888
  remote_platform_arch: "linux/arm64/v8"
  local_platform_arch: "linux/arm64/v8"
  docker_registry_address: "host.internal:6789/clue"
  result_base_path: "results/"
  workloads: ["shaped"]