config:
  docker_registry_address: registry:5000/clue
  experiment_timeout: 152
  local_platform_arch: linux/arm64/v8
  local_port: 5002
  local_public_ip: registry
  prometheus_url: http://clue-cluster-control-plane:30090
  remote_platform_arch: linux/arm64/v8
  target_utilization: 70
