config:
  prometheus_url: "http://localhost:9090"  # minikube
  docker_user: "registry:5000/clue"
  local_public_ip: "host.internal"
  local_port: 8888
  remote_platform_arch: "linux/arm64/v8"
  local_platform_arch: "linux/arm64/v8"
  docker_registry_address: "registry:5000/clue"
  result_base_path: "results/"
  workloads: ["shaped"]