name: "clue2"

services:
  # The main image registry
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - registry-data:/var/lib/registry

  # The CLUE dashboard
  clue-dashboard:
    image: ghcr.io/clue2-sose25/clue2/clue-dashboard:latest
    build: 
      context: ./clue_dashboard
      dockerfile: Dockerfile
    container_name: clue-dashboard
    ports:
      - "5001:80"
    # Uncomment when deployer is transitioned into a service 
    # depends_on:
    #   - clue-deployer
    environment:
      DOCKER_BUILDKIT: 1

  # The main CLUE deployer
  clue-deployer:
    image: ghcr.io/clue2-sose25/clue2/clue-deployer:latest
    build:
      context: .
      dockerfile: ./clue_deployer/Dockerfile
    container_name: clue-deployer
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      SUT_NAME: ${SUT_NAME}
      EXPERIMENT_NAME: ${EXPERIMENT_NAME}
      DEPLOY_ONLY: ${DEPLOY_ONLY}
    volumes:
      # CLUE Configs
      - ./clue-config.yaml:/app/clue-config.yaml
      - ./sut_configs:/app/sut_configs
      # Cluster configs
      - ~/.kube:/root/.kube:ro
      # use this line if you want to use minikube - make sure to run the script in localClusterConfig/minikube first and commend out the line above
      # - ./localClusterConfig/minikube/minikube_kube_config:/root/.kube/config:ro
    # needed for linux systems
    extra_hosts:
      - "host.internal:host-gateway"
    
  # The optional Teastore builder
  teastore-builder:
    image: ghcr.io/clue2-sose25/clue2/teastore-builder:latest
    build:
      context: .
      dockerfile: ./clue_builders/teastore/Dockerfile
    container_name: teastore-builder
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      TEASTORE_EXP_NAME: ${TEASTORE_EXP_NAME}
    volumes:
      # CLUE Configs
      - ./clue-config.yaml:/app/clue-config.yaml
      - ./sut_configs:/app/sut_configs

  # The optional Open Telemetry Shop builder
  ots-builder:
    image: ghcr.io/clue2-sose25/clue2/ots-builder:latest
    build:
      context: .
      dockerfile: ./clue_builders/ots/Dockerfile
    container_name: ots-builder
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      OTS_EXP_NAME: ${OTS_EXP_NAME}
    volumes:
      # CLUE Configs
      - ./clue-config.yaml:/app/clue-config.yaml
      - ./sut_configs:/app/sut_configs

volumes:
  registry-data:
