name: "clue2"

services:
  # The main image registry
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "6789:5000"
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - registry-data:/var/lib/registry

  # The optional Teastore builder
  teastore-builder:
    image: ghcr.io/clue2-sose25/clue2/teastore-builder:latest
    build:
      context: .
      dockerfile: ./clue_builders/teastore/Dockerfile
    container_name: teastore-builder
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      SUT_EXPERIMENT: baseline
    
  clue-deployer:
    image: ghcr.io/clue2-sose25/clue2/clue-deployer:latest
    build:
      context: .
      dockerfile: ./clue_deployer/Dockerfile
    container_name: clue-deployer
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      SUT: teastore
      EXPERIMENT: baseline
      DEPLOY_ONLY: false
    volumes:
      # - ~/.kube:/root/.kube:ro
      # use this line if you want to use minikube - make sure to run the script in localClusterConfig/minikube first and commend out the line above
      - ./localClusterConfig/minikube/minikube_kube_config:/root/.kube/config:ro
    # needed for linux systems
    extra_hosts:
      - "host.internal:host-gateway"

volumes:
  registry-data:
