name: "clue2"

services:
  # The main image registry
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "6789:5000"
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - registry-data:/var/lib/registry

  # The optional Teastore builder
  teastore-builder:
    image: ghcr.io/clue2-sose25/clue2/teastore-builder:latest
    build:
      context: .
      dockerfile: ./clue_builders/teastore/Dockerfile
    container_name: teastore-builder
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      SUT_EXPERIMENT: baseline
    
  clue-deployer:
    image: ghcr.io/clue2-sose25/clue2/clue-deployer:latest
    build:
      context: .
      dockerfile: ./clue_deployer/Dockerfile
    container_name: clue-deployer
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - ~/.kube:/root/.kube:ro
    # needed for linux systems
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  registry-data:
