name: "clue2"

services:
  # The main image registry
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "9000:5000"
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - clue2

  # The CLUE webui
  clue-webui:
    image: ghcr.io/clue2-sose25/clue2/clue-webui:latest
    build:
      context: ./clue_webui
      dockerfile: Dockerfile
    container_name: clue-webui
    ports:
      - "5001:80"
    environment:
      DOCKER_BUILDKIT: 1
    networks:
      - clue2

  # The main CLUE deployer
  clue-deployer:
    image: ghcr.io/clue2-sose25/clue2/clue-deployer:latest
    build:
      context: .
      dockerfile: ./clue_deployer/Dockerfile
    container_name: clue-deployer
    ports:
      - "9001:8000"
      - "5678:5678"
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      SUT: ${SUT}
      VARIANTS: ${VARIANTS}
      WORKLOADS: ${WORKLOADS}
      N_ITERATIONS: ${N_ITERATIONS}
      DEPLOY_ONLY: ${DEPLOY_ONLY}
      DEPLOY_AS_SERVICE: ${DEPLOY_AS_SERVICE}
      KUBE_CONFIG: ${KUBE_CONFIG}
      PATCH_LOCAL_CLUSTER: ${PATCH_LOCAL_CLUSTER:-true}
    volumes:
      # CLUE Configs
      - ./clue-config.yaml:/app/clue-config.yaml
      - ./sut_configs:/app/sut_configs
      # Cluster configs
      - ${KUBECONFIG_FILE:-~/.kube/config}:/root/.kube/config:ro
      # Results
      - results-deployer-data:/app/data
    networks:
      - clue2

  # The optional Teastore builder
  teastore-builder:
    image: ghcr.io/clue2-sose25/clue2/teastore-builder:latest
    profiles:
      - teastore
    build:
      context: .
      dockerfile: ./clue_builders/teastore/Dockerfile
    container_name: teastore-builder
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      TEASTORE_EXP_NAME: ${TEASTORE_EXP_NAME}
    volumes:
      # CLUE Configs
      - ./clue-config.yaml:/app/clue-config.yaml
      - ./sut_configs:/app/sut_configs
    networks:
      - clue2

  # The optional Open Telemetry Shop builder
  ots-builder:
    image: ghcr.io/clue2-sose25/clue2/ots-builder:latest
    profiles:
      - ots
    build:
      context: .
      dockerfile: ./clue_builders/ots/Dockerfile
    container_name: ots-builder
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      OTS_EXP_NAME: ${OTS_EXP_NAME}
    volumes:
      # CLUE Configs
      - ./clue-config.yaml:/app/clue-config.yaml
      - ./sut_configs:/app/sut_configs
    networks:
      - clue2

  # The optional Toystore builder
  toystore-builder:
    image: ghcr.io/clue2-sose25/clue2/toystore-builder:latest
    profiles:
      - toystore
    build:
      context: .
      dockerfile: ./clue_builders/toystore/Dockerfile
    container_name: toystore-builder
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
      OTS_EXP_NAME: ${OTS_EXP_NAME}
    volumes:
      # CLUE Configs
      - ./clue-config.yaml:/app/clue-config.yaml
      - ./sut_configs:/app/sut_configs
    networks:
      - clue2

  clue-loadgenerator-builder:
    image: ghcr.io/clue2-sose25/clue2/loadgenerator-builder:latest
    profiles:
      - toystore
      - teastore
      - ots
    build:
      context: .
      dockerfile: ./clue_loadgenerator/builder/Dockerfile
    container_name: loadgenerator-builder
    privileged: true
    depends_on:
      - registry
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - ./clue-config.yaml:/app/clue-config.yaml
      - ./sut_configs:/app/sut_configs
      - ./clue_loadgenerator:/app/clue_loadgenerator
    networks:
      - clue2

volumes:
  registry-data:
  results-deployer-data:

networks:
  clue2:
    name: clue2
    external: false
    driver: bridge
