apiVersion: 1
datasources:
- access: proxy
  basicAuth: false
  editable: true
  isDefault: true
  jsonData:
    httpMethod: POST
    timeInterval: 5s
  name: Prometheus
  type: prometheus
  url: http://clue-cluster-control-plane:30090
