---
apiVersion: v1
kind: Service
metadata:
  name: clue-webui
spec:
  type: {{ .Values.clueDeployer.service.type | default "ClusterIP" }}
  selector:
    app: clue-webui
  ports:
    - port: {{ .Values.clueWebui.service.port }}
      targetPort: 80
      {{- if and .Values.clueWebui.service.nodePort (ne .Values.clueWebui.service.type "ClusterIP") }}
      nodePort: {{ .Values.clueWebui.service.nodePort }}
      {{- end }}