apiVersion: batch/v1
kind: Job
metadata:
  name: clue-loadgenerator
spec:
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      restartPolicy: Never
{{- $sut := .Values.clueDeployer.env.SUT | default "sut" }}
{{- $paths := list }}
{{- range $name, $_ := .Values.loadGenerator.workloadFiles }}
{{- $paths = append $paths (printf "/app/sut_configs/workloads/%s/%s" $sut $name) }}
{{- end }}
      containers:
        - name: loadgenerator
          image: "{{ .Values.imageRegistry }}/{{ .Values.loadGenerator.image }}:{{ .Values.loadGenerator.tag }}"
          env:
            - name: SUT_NAME
              value: "{{ $sut }}"
            - name: LOCUST_FILE
              value: "{{ join $paths "," }}"
          volumeMounts:
            - name: workload-files
              mountPath: "/app/sut_configs/workloads/{{ $sut }}"
      volumes:
        - name: workload-files
          configMap:
            name: loadgenerator-workload