apiVersion: batch/v1
kind: Job
metadata:
  name: clue-deployer-job
spec:
  template:
    metadata:
      labels:
        app: clue-deployer
    spec:
      serviceAccountName: {{ .Values.clueDeployer.serviceAccountName }}
      restartPolicy: Never
      containers:
        - name: clue-deployer
          image: "{{ .Values.imageRegistry }}/{{ .Values.clueDeployer.image }}:{{ .Values.clueDeployer.tag }}"
          env:
            - name: DEPLOY_AS_SERVICE
              value: "false"
          envFrom:
            - configMapRef:
                name: clue-config
            - secretRef:
                name: clue-secrets
          volumeMounts:
            - name: results
              mountPath: /app/data
      volumes:
        - name: results
          emptyDir: {}