apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clue-data
  labels:
    {{- include "clue.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi