#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: clue-data-pv
#  name-space: st-cp25clue2
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: ""       # empty for static provisioning
#  hostPath:
#    path: /tmp/clue-data
#    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clue-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi