#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: clue-data-pv
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: ""       # empty for static provisioning
#  hostPath:
#    path: /mnt/data/clue
#    type: DirectoryOrCreate
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clue-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi