{{- if .Values.rbac.create }}
{{- $helmDriver := default "configmap" .Values.clueDeployer.env.HELM_DRIVER }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clue-deployer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clue-deployer-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clue-deployer-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clue-deployer-cluster-role
subjects:
  - kind: ServiceAccount
    name: clue-deployer
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clue-deployer-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
{{- if eq $helmDriver "secret" }}
      - secrets
{{- end }}
    verbs: ["create", "delete", "list", "get", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["create", "delete", "list", "get", "patch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "delete", "list", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clue-deployer-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clue-deployer-role
subjects:
  - kind: ServiceAccount
    name: clue-deployer
    namespace: {{ .Release.Namespace }}
{{- if .Values.sutNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clue-deployer-role
  namespace: {{ .Values.sutNamespace }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
{{- if eq $helmDriver "secret" }}
      - secrets
{{- end }}
    verbs: ["create", "delete", "list", "get", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["create", "delete", "list", "get", "patch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "delete", "list", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clue-deployer-binding
  namespace: {{ .Values.sutNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clue-deployer-role
subjects:
  - kind: ServiceAccount
    name: clue-deployer
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}