global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kepler'
    static_configs:
      - targets: ['kepler-exporter:8888']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'prometheus-agent'
    static_configs:
      - targets: ['prometheus-agent:8000']
