config:
  namespace: "tea-bench"
  sut_path: "teastore"
  target_host: "http://teastore-webui/tools.descartes.teastore.webui"
  default_resource_limits:
    cpu: 1000
    memory: 1024
  workload_settings: {}
  timeout_duration: 3600  # 1 hour in seconds
  wait_before_workloads: 180  # 3 minutes in seconds
  wait_after_workloads: 180  # 3 minutes in seconds
  tags: []
  num_iterations: 1
  
services:
  - name: "teastore-auth"
    resource_limits:
      cpu: 450
      memory: 1024
  - name: "teastore-webui"
    resource_limits:
      cpu: 1000
      memory: 1500
  - name: "teastore-recommender"
    resource_limits:
      cpu: 1000
      memory: 1024
  - name: "teastore-image"
    resource_limits:
      cpu: 1000
      memory: 1500
  - name: "teastore-all"
    resource_limits:
      cpu: 1000
      memory: 2048


experiments:
  - name: "baseline"
    target_branch: "vanilla"
    colocated_workload: true
    critical_services: ['teastore-auth', 'teastore-registry', 'teastore-webui']
  # - name: "serverless"
  #   target_branch: "serverless"
  #   colocated_workload: true
  #   critical_services: ["teastore-registry", "teastore-webui"]
  
