# example values for running the toystore SUT
imageRegistry: ghcr.io/clue2-sose25
imagePullPolicy: Always
sutConfigFileName: toystore.yaml
sutConfig: |
  config:
    # The name of the SUT
    sut: "toystore"
    namespace: "st-cp25clue2"
    sut_git_repo: "https://github.com/clue2-sose25/sustainable_toystore"
    sut_path: "toystore"
    helm_chart_path: "toystore/toystore"
    values_yaml_name: "values.yaml"
    workload_target: "teastore-webui"
    application_endpoint_path: "/tools.descartes.teastore.webui"
    default_resource_limits:
      cpu: 1000
      memory: 1024
    wait_before_workloads: 30
    wait_after_workloads: 30
  helm_replacements: []
  workloads:
    - name: "shaped"
      description: "Workload with custom load shape behavior."
      timeout_duration: 120
      workload_runtime: 64
      workload_settings: {}
      locust_files:
        - "sut_configs/workloads/toystore/locustfile.py"
  resource_limits: []
  variants:
    - name: "baseline"
      description: "A ToyStore application storing its data in a local SQLite DB"
      target_branch: "baseline"
      colocated_workload: true
      critical_services: ["toystore-frontend", "toystore-backend"]
      autoscaling: "cpu"
    - name: "postgres"
      description: "A ToyStore application using external Postgres DB"
      target_branch: "postgres"
      colocated_workload: true
      critical_services: ["toystore-frontend", "toystore-backend", "toystore-db"]
      autoscaling: "cpu"
clueConfig: |
  config:
    experiment_timeout: 150
    prometheus_url: "http://192.168.1.106:9090"
    docker_registry_address: ghcr.io/clue2-sose25
    local_public_ip: "registry"
    local_port: 5000
    remote_platform_arch: "linux/arm64/v8"
    local_platform_arch: "linux/arm64/v8"
    target_utilization: 70
clueDeployer:
  enabled: true
  image: clue2-deployer
  tag: pr-test
  serviceAccountName: st-cp25clue2-user  
  service:
    port: 8000
    type: ClusterIP # Change to NodePort if needed or LoadBalancer if need to access with IP_NODE:PORT
    nodePort: 30501
  probes:
    path: /api/health
  env:
    DEPLOY_ONLY: "false"
    N_ITERATIONS: "1"
    SUT: toystore
    VARIANTS: baseline
    WORKLOADS: shaped
    PRECONFIGURE_CLUSTER: "false"
    DEPLOY_AS_SERVICE: "false"
    HELM_DRIVER: configmap
  job:
    enabled: true
clueWebui:
  enabled: true
  image: clue2-webui
  tag: pr-test
  service:
    port: 80
    type: ClusterIP # Change to NodePort if needed or LoadBalancer if need to access with IP_NODE:PORT
    nodePort: 30501
  env:
    API_BASE_URL: http://clue-deployer:8000
loadGenerator:
  jobEnabled: false
  image: clue2-loadgenerator-builder
  tag: latest
  # Set this to mount a folder path within the chart to include all locust files
  workloadDir: default_workloads_toystore
ingress:
  enabled: false
  host: clue.example.com
  tls: false
rbac:
  create: false
