# example values for customizing the CLUE Helm chart
imageRegistry: ghcr.io/your-org
sutConfigFileName: example-sut.yaml
sutConfig: |
  config:
    sut: example
    namespace: example
  workloads: []
clueConfig: |
  config:
    experiment_timeout: 150
    prometheus_url: http://prometheus.example.com
    docker_registry_address: ghcr.io/your-org/clue
    local_public_ip: registry
    local_port: 5000
    remote_platform_arch: linux/amd64
    local_platform_arch: linux/amd64
    target_utilization: 70
clueDeployer:
  image: clue2-deployer
  tag: latest
  serviceAccountName: clue-deployer
  service:
    port: 8000
  probes:
    path: /api/health
  env:
    DEPLOY_ONLY: "false"
    N_ITERATIONS: "1"
    SUT: example
    VARIANTS: baseline
    WORKLOADS: shaped
    PRECONFIGURE_CLUSTER: "false"
clueWebui:
  image: clue2-webui
  tag: latest
  service:
    port: 80
  env:
    API_BASE_URL: http://clue-deployer:8000
loadGenerator:
  image: clue-loadgenerator
  tag: latest
  # set this to a folder path within the chart to include all Locust files
  workloadDir: extra-workloads
  workloadFiles:
    example.py: |
      from locust import HttpUser, task

      class Example(HttpUser):
          @task
          def index(self):
              self.client.get("/")
ingress:
  enabled: true
  host: clue.example.com
  tls: false
