# RBAC resources for running the CLUE deployer manually
# Apply with: kubectl apply -f clue_deployer/k8s/clue-deployer-rbac.yaml
# Adjust the namespace as needed. These defaults match the Helm chart.
# change the namespace in the metadata section if you want to deploy it in a different namespace!!

apiVersion: v1
kind: ServiceAccount
metadata:
  name: clue-deployer
  namespace: clue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clue-deployer-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clue-deployer-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clue-deployer-cluster-role
subjects:
  - kind: ServiceAccount
    name: clue-deployer
    namespace: clue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clue-deployer-role
  namespace: clue
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["create", "delete", "deletecollection", "list", "get", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["create", "delete", "list", "get", "patch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "delete", "list", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clue-deployer-binding
  namespace: clue
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clue-deployer-role
subjects:
  - kind: ServiceAccount
    name: clue-deployer
    namespace: clue