name: Build and Push Helm Chart

on:
  push:
    branches: ["dev", "main"]
    paths:
      - "clue_helm/**"
  pull_request:
    branches: ["dev"]
    paths:
      - "clue_helm/**"

permissions:
  contents: read
  packages: write

jobs:
  build_clue_helm:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: helm
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Compute short Git SHA
        id: vars
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "::set-output name=short_sha::${GITHUB_SHA::7}"
      - name: Package chart
        run: |
          CHART_VERSION=0.1.0-${SHORT_SHA}
          helm package clue_helm --destination . --version $CHART_VERSION
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
      - name: Push chart
        run: |
          CHART_VERSION=0.1.0-${SHORT_SHA}
          helm push clue-$CHART_VERSION.tgz oci://ghcr.io/julianlegler/clue2-${IMAGE_NAME}